#!/bin/bash
shopt -u dotglob

sudo chown -R jw *
sudo chown -R jw .git
sudo chown -R www-data questions
sudo chmod -R a+rw questions
sudo chown -R www-data id
sudo chmod -R a+rw  id
sudo chown -R www-data astro
sudo chmod -R a+rw  astro
sudo chmod -R 777 log
sudo chmod -R 777 charting/sessions  
sudo chmod -R 777 tmp
